name: Deployment

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]
      

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.7.2
    - name: Setup .NET Core SDK
      with:
        dotnet-version: "5.0.x"
        source-url: # optional
        owner: # optional
        config-file: # optional
      run: dotnet build ChatApp